// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.19.4
// source: cms_category.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// --------------------------------CMS内容分类表--------------------------------
type CmsCategory struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title      string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"` //分类名称（如：资讯、产品、公告）
	CateGoryId int64  `protobuf:"varint,2,opt,name=cate_gory_id,json=cateGoryId,proto3" json:"cate_gory_id,omitempty"`
	Content    string `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *CmsCategory) Reset() {
	*x = CmsCategory{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cms_category_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CmsCategory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmsCategory) ProtoMessage() {}

func (x *CmsCategory) ProtoReflect() protoreflect.Message {
	mi := &file_cms_category_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmsCategory.ProtoReflect.Descriptor instead.
func (*CmsCategory) Descriptor() ([]byte, []int) {
	return file_cms_category_proto_rawDescGZIP(), []int{0}
}

func (x *CmsCategory) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CmsCategory) GetCateGoryId() int64 {
	if x != nil {
		return x.CateGoryId
	}
	return 0
}

func (x *CmsCategory) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type AddCmsCategoryReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title      string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"` //分类名称（如：资讯、产品、公告）
	CateGoryId int64  `protobuf:"varint,2,opt,name=cate_gory_id,json=cateGoryId,proto3" json:"cate_gory_id,omitempty"`
	Content    string `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *AddCmsCategoryReq) Reset() {
	*x = AddCmsCategoryReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cms_category_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddCmsCategoryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCmsCategoryReq) ProtoMessage() {}

func (x *AddCmsCategoryReq) ProtoReflect() protoreflect.Message {
	mi := &file_cms_category_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCmsCategoryReq.ProtoReflect.Descriptor instead.
func (*AddCmsCategoryReq) Descriptor() ([]byte, []int) {
	return file_cms_category_proto_rawDescGZIP(), []int{1}
}

func (x *AddCmsCategoryReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AddCmsCategoryReq) GetCateGoryId() int64 {
	if x != nil {
		return x.CateGoryId
	}
	return 0
}

func (x *AddCmsCategoryReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type AddCmsCategoryResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *AddCmsCategoryResp) Reset() {
	*x = AddCmsCategoryResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cms_category_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddCmsCategoryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCmsCategoryResp) ProtoMessage() {}

func (x *AddCmsCategoryResp) ProtoReflect() protoreflect.Message {
	mi := &file_cms_category_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCmsCategoryResp.ProtoReflect.Descriptor instead.
func (*AddCmsCategoryResp) Descriptor() ([]byte, []int) {
	return file_cms_category_proto_rawDescGZIP(), []int{2}
}

func (x *AddCmsCategoryResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdateCmsCategoryReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`         //分类ID（主键）
	Name   string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`      //分类名称（如：资讯、产品、公告）
	Code   string `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`      //分类编码（唯一标识，如：news、product）
	Sort   int64  `protobuf:"varint,4,opt,name=sort,proto3" json:"sort,omitempty"`     //排序值（数字越小越靠前）
	Status int64  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"` //状态（1=启用，0=禁用）
}

func (x *UpdateCmsCategoryReq) Reset() {
	*x = UpdateCmsCategoryReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cms_category_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateCmsCategoryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCmsCategoryReq) ProtoMessage() {}

func (x *UpdateCmsCategoryReq) ProtoReflect() protoreflect.Message {
	mi := &file_cms_category_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCmsCategoryReq.ProtoReflect.Descriptor instead.
func (*UpdateCmsCategoryReq) Descriptor() ([]byte, []int) {
	return file_cms_category_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateCmsCategoryReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateCmsCategoryReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateCmsCategoryReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *UpdateCmsCategoryReq) GetSort() int64 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *UpdateCmsCategoryReq) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type UpdateCmsCategoryResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *UpdateCmsCategoryResp) Reset() {
	*x = UpdateCmsCategoryResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cms_category_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateCmsCategoryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCmsCategoryResp) ProtoMessage() {}

func (x *UpdateCmsCategoryResp) ProtoReflect() protoreflect.Message {
	mi := &file_cms_category_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCmsCategoryResp.ProtoReflect.Descriptor instead.
func (*UpdateCmsCategoryResp) Descriptor() ([]byte, []int) {
	return file_cms_category_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateCmsCategoryResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DelCmsCategoryReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` //id
}

func (x *DelCmsCategoryReq) Reset() {
	*x = DelCmsCategoryReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cms_category_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelCmsCategoryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelCmsCategoryReq) ProtoMessage() {}

func (x *DelCmsCategoryReq) ProtoReflect() protoreflect.Message {
	mi := &file_cms_category_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelCmsCategoryReq.ProtoReflect.Descriptor instead.
func (*DelCmsCategoryReq) Descriptor() ([]byte, []int) {
	return file_cms_category_proto_rawDescGZIP(), []int{5}
}

func (x *DelCmsCategoryReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DelCmsCategoryResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *DelCmsCategoryResp) Reset() {
	*x = DelCmsCategoryResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cms_category_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelCmsCategoryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelCmsCategoryResp) ProtoMessage() {}

func (x *DelCmsCategoryResp) ProtoReflect() protoreflect.Message {
	mi := &file_cms_category_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelCmsCategoryResp.ProtoReflect.Descriptor instead.
func (*DelCmsCategoryResp) Descriptor() ([]byte, []int) {
	return file_cms_category_proto_rawDescGZIP(), []int{6}
}

func (x *DelCmsCategoryResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetCmsCategoryByIdReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` //id
}

func (x *GetCmsCategoryByIdReq) Reset() {
	*x = GetCmsCategoryByIdReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cms_category_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCmsCategoryByIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCmsCategoryByIdReq) ProtoMessage() {}

func (x *GetCmsCategoryByIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_cms_category_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCmsCategoryByIdReq.ProtoReflect.Descriptor instead.
func (*GetCmsCategoryByIdReq) Descriptor() ([]byte, []int) {
	return file_cms_category_proto_rawDescGZIP(), []int{7}
}

func (x *GetCmsCategoryByIdReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetCmsCategoryByIdResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CmsCategory *CmsCategory `protobuf:"bytes,1,opt,name=cmsCategory,proto3" json:"cmsCategory,omitempty"` //cmsCategory
}

func (x *GetCmsCategoryByIdResp) Reset() {
	*x = GetCmsCategoryByIdResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cms_category_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCmsCategoryByIdResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCmsCategoryByIdResp) ProtoMessage() {}

func (x *GetCmsCategoryByIdResp) ProtoReflect() protoreflect.Message {
	mi := &file_cms_category_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCmsCategoryByIdResp.ProtoReflect.Descriptor instead.
func (*GetCmsCategoryByIdResp) Descriptor() ([]byte, []int) {
	return file_cms_category_proto_rawDescGZIP(), []int{8}
}

func (x *GetCmsCategoryByIdResp) GetCmsCategory() *CmsCategory {
	if x != nil {
		return x.CmsCategory
	}
	return nil
}

type SearchCmsCategoryReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page int64 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"` //page
	Size int64 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *SearchCmsCategoryReq) Reset() {
	*x = SearchCmsCategoryReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cms_category_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchCmsCategoryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchCmsCategoryReq) ProtoMessage() {}

func (x *SearchCmsCategoryReq) ProtoReflect() protoreflect.Message {
	mi := &file_cms_category_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchCmsCategoryReq.ProtoReflect.Descriptor instead.
func (*SearchCmsCategoryReq) Descriptor() ([]byte, []int) {
	return file_cms_category_proto_rawDescGZIP(), []int{9}
}

func (x *SearchCmsCategoryReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchCmsCategoryReq) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type SearchCmsCategoryResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CmsCategory []*CmsCategory `protobuf:"bytes,1,rep,name=cmsCategory,proto3" json:"cmsCategory,omitempty"` //cmsCategory
}

func (x *SearchCmsCategoryResp) Reset() {
	*x = SearchCmsCategoryResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cms_category_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchCmsCategoryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchCmsCategoryResp) ProtoMessage() {}

func (x *SearchCmsCategoryResp) ProtoReflect() protoreflect.Message {
	mi := &file_cms_category_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchCmsCategoryResp.ProtoReflect.Descriptor instead.
func (*SearchCmsCategoryResp) Descriptor() ([]byte, []int) {
	return file_cms_category_proto_rawDescGZIP(), []int{10}
}

func (x *SearchCmsCategoryResp) GetCmsCategory() []*CmsCategory {
	if x != nil {
		return x.CmsCategory
	}
	return nil
}

var File_cms_category_proto protoreflect.FileDescriptor

var file_cms_category_proto_rawDesc = []byte{
	0x0a, 0x12, 0x63, 0x6d, 0x73, 0x5f, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x72, 0x63, 0x65, 0x22,
	0x5f, 0x0a, 0x0b, 0x43, 0x6d, 0x73, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0c, 0x63, 0x61, 0x74, 0x65, 0x5f, 0x67, 0x6f, 0x72,
	0x79, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x63, 0x61, 0x74, 0x65,
	0x47, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x22, 0x65, 0x0a, 0x11, 0x41, 0x64, 0x64, 0x43, 0x6d, 0x73, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0c, 0x63,
	0x61, 0x74, 0x65, 0x5f, 0x67, 0x6f, 0x72, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0a, 0x63, 0x61, 0x74, 0x65, 0x47, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x12, 0x18, 0x0a,
	0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x2e, 0x0a, 0x12, 0x41, 0x64, 0x64, 0x43, 0x6d,
	0x73, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x7a, 0x0a, 0x14, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x43, 0x6d, 0x73, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x22, 0x31, 0x0a, 0x15, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6d, 0x73,
	0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x23, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x43, 0x6d, 0x73,
	0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x2e, 0x0a, 0x12, 0x44,
	0x65, 0x6c, 0x43, 0x6d, 0x73, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x27, 0x0a, 0x15, 0x47,
	0x65, 0x74, 0x43, 0x6d, 0x73, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x42, 0x79, 0x49,
	0x64, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x52, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x43, 0x6d, 0x73, 0x43, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x38,
	0x0a, 0x0b, 0x63, 0x6d, 0x73, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x72, 0x63, 0x65, 0x2e,
	0x43, 0x6d, 0x73, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x0b, 0x63, 0x6d, 0x73,
	0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x22, 0x3e, 0x0a, 0x14, 0x53, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x43, 0x6d, 0x73, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71,
	0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04,
	0x70, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x22, 0x51, 0x0a, 0x15, 0x53, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x43, 0x6d, 0x73, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x38, 0x0a, 0x0b, 0x63, 0x6d, 0x73, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x72,
	0x63, 0x65, 0x2e, 0x43, 0x6d, 0x73, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x0b,
	0x63, 0x6d, 0x73, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x32, 0xbb, 0x03, 0x0a, 0x10,
	0x45, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x72, 0x63, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x4d, 0x0a, 0x0e, 0x41, 0x64, 0x64, 0x43, 0x6d, 0x73, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x12, 0x1c, 0x2e, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x72, 0x63, 0x65, 0x2e, 0x41,
	0x64, 0x64, 0x43, 0x6d, 0x73, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71,
	0x1a, 0x1d, 0x2e, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x72, 0x63, 0x65, 0x2e, 0x41, 0x64, 0x64,
	0x43, 0x6d, 0x73, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x56, 0x0a, 0x11, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6d, 0x73, 0x43, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x12, 0x1f, 0x2e, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x72, 0x63, 0x65,
	0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6d, 0x73, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x20, 0x2e, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x72, 0x63,
	0x65, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6d, 0x73, 0x43, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x12, 0x4d, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x43, 0x6d,
	0x73, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x1c, 0x2e, 0x65, 0x63, 0x6f, 0x6d,
	0x6d, 0x65, 0x72, 0x63, 0x65, 0x2e, 0x44, 0x65, 0x6c, 0x43, 0x6d, 0x73, 0x43, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x1d, 0x2e, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65,
	0x72, 0x63, 0x65, 0x2e, 0x44, 0x65, 0x6c, 0x43, 0x6d, 0x73, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x12, 0x59, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x43, 0x6d, 0x73,
	0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x42, 0x79, 0x49, 0x64, 0x12, 0x20, 0x2e, 0x65,
	0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x72, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6d, 0x73, 0x43,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x21,
	0x2e, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x72, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6d,
	0x73, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x56, 0x0a, 0x11, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x43, 0x6d, 0x73, 0x43, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x1f, 0x2e, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x72,
	0x63, 0x65, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x43, 0x6d, 0x73, 0x43, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x20, 0x2e, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65,
	0x72, 0x63, 0x65, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x43, 0x6d, 0x73, 0x43, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cms_category_proto_rawDescOnce sync.Once
	file_cms_category_proto_rawDescData = file_cms_category_proto_rawDesc
)

func file_cms_category_proto_rawDescGZIP() []byte {
	file_cms_category_proto_rawDescOnce.Do(func() {
		file_cms_category_proto_rawDescData = protoimpl.X.CompressGZIP(file_cms_category_proto_rawDescData)
	})
	return file_cms_category_proto_rawDescData
}

var file_cms_category_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_cms_category_proto_goTypes = []any{
	(*CmsCategory)(nil),            // 0: ecommerce.CmsCategory
	(*AddCmsCategoryReq)(nil),      // 1: ecommerce.AddCmsCategoryReq
	(*AddCmsCategoryResp)(nil),     // 2: ecommerce.AddCmsCategoryResp
	(*UpdateCmsCategoryReq)(nil),   // 3: ecommerce.UpdateCmsCategoryReq
	(*UpdateCmsCategoryResp)(nil),  // 4: ecommerce.UpdateCmsCategoryResp
	(*DelCmsCategoryReq)(nil),      // 5: ecommerce.DelCmsCategoryReq
	(*DelCmsCategoryResp)(nil),     // 6: ecommerce.DelCmsCategoryResp
	(*GetCmsCategoryByIdReq)(nil),  // 7: ecommerce.GetCmsCategoryByIdReq
	(*GetCmsCategoryByIdResp)(nil), // 8: ecommerce.GetCmsCategoryByIdResp
	(*SearchCmsCategoryReq)(nil),   // 9: ecommerce.SearchCmsCategoryReq
	(*SearchCmsCategoryResp)(nil),  // 10: ecommerce.SearchCmsCategoryResp
}
var file_cms_category_proto_depIdxs = []int32{
	0,  // 0: ecommerce.GetCmsCategoryByIdResp.cmsCategory:type_name -> ecommerce.CmsCategory
	0,  // 1: ecommerce.SearchCmsCategoryResp.cmsCategory:type_name -> ecommerce.CmsCategory
	1,  // 2: ecommerce.EcommerceService.AddCmsCategory:input_type -> ecommerce.AddCmsCategoryReq
	3,  // 3: ecommerce.EcommerceService.UpdateCmsCategory:input_type -> ecommerce.UpdateCmsCategoryReq
	5,  // 4: ecommerce.EcommerceService.DelCmsCategory:input_type -> ecommerce.DelCmsCategoryReq
	7,  // 5: ecommerce.EcommerceService.GetCmsCategoryById:input_type -> ecommerce.GetCmsCategoryByIdReq
	9,  // 6: ecommerce.EcommerceService.SearchCmsCategory:input_type -> ecommerce.SearchCmsCategoryReq
	2,  // 7: ecommerce.EcommerceService.AddCmsCategory:output_type -> ecommerce.AddCmsCategoryResp
	4,  // 8: ecommerce.EcommerceService.UpdateCmsCategory:output_type -> ecommerce.UpdateCmsCategoryResp
	6,  // 9: ecommerce.EcommerceService.DelCmsCategory:output_type -> ecommerce.DelCmsCategoryResp
	8,  // 10: ecommerce.EcommerceService.GetCmsCategoryById:output_type -> ecommerce.GetCmsCategoryByIdResp
	10, // 11: ecommerce.EcommerceService.SearchCmsCategory:output_type -> ecommerce.SearchCmsCategoryResp
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_cms_category_proto_init() }
func file_cms_category_proto_init() {
	if File_cms_category_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cms_category_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*CmsCategory); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cms_category_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*AddCmsCategoryReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cms_category_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*AddCmsCategoryResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cms_category_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateCmsCategoryReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cms_category_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateCmsCategoryResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cms_category_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*DelCmsCategoryReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cms_category_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*DelCmsCategoryResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cms_category_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*GetCmsCategoryByIdReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cms_category_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*GetCmsCategoryByIdResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cms_category_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*SearchCmsCategoryReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cms_category_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*SearchCmsCategoryResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cms_category_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cms_category_proto_goTypes,
		DependencyIndexes: file_cms_category_proto_depIdxs,
		MessageInfos:      file_cms_category_proto_msgTypes,
	}.Build()
	File_cms_category_proto = out.File
	file_cms_category_proto_rawDesc = nil
	file_cms_category_proto_goTypes = nil
	file_cms_category_proto_depIdxs = nil
}
