// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.19.4
// source: cms_category.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	EcommerceService_AddCmsCategory_FullMethodName     = "/ecommerce.EcommerceService/AddCmsCategory"
	EcommerceService_UpdateCmsCategory_FullMethodName  = "/ecommerce.EcommerceService/UpdateCmsCategory"
	EcommerceService_DelCmsCategory_FullMethodName     = "/ecommerce.EcommerceService/DelCmsCategory"
	EcommerceService_GetCmsCategoryById_FullMethodName = "/ecommerce.EcommerceService/GetCmsCategoryById"
	EcommerceService_SearchCmsCategory_FullMethodName  = "/ecommerce.EcommerceService/SearchCmsCategory"
)

// EcommerceServiceClient is the client API for EcommerceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EcommerceServiceClient interface {
	// -----------------------CMS内容分类表-----------------------
	AddCmsCategory(ctx context.Context, in *AddCmsCategoryReq, opts ...grpc.CallOption) (*AddCmsCategoryResp, error)
	UpdateCmsCategory(ctx context.Context, in *UpdateCmsCategoryReq, opts ...grpc.CallOption) (*UpdateCmsCategoryResp, error)
	DelCmsCategory(ctx context.Context, in *DelCmsCategoryReq, opts ...grpc.CallOption) (*DelCmsCategoryResp, error)
	GetCmsCategoryById(ctx context.Context, in *GetCmsCategoryByIdReq, opts ...grpc.CallOption) (*GetCmsCategoryByIdResp, error)
	SearchCmsCategory(ctx context.Context, in *SearchCmsCategoryReq, opts ...grpc.CallOption) (*SearchCmsCategoryResp, error)
}

type ecommerceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEcommerceServiceClient(cc grpc.ClientConnInterface) EcommerceServiceClient {
	return &ecommerceServiceClient{cc}
}

func (c *ecommerceServiceClient) AddCmsCategory(ctx context.Context, in *AddCmsCategoryReq, opts ...grpc.CallOption) (*AddCmsCategoryResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddCmsCategoryResp)
	err := c.cc.Invoke(ctx, EcommerceService_AddCmsCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ecommerceServiceClient) UpdateCmsCategory(ctx context.Context, in *UpdateCmsCategoryReq, opts ...grpc.CallOption) (*UpdateCmsCategoryResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateCmsCategoryResp)
	err := c.cc.Invoke(ctx, EcommerceService_UpdateCmsCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ecommerceServiceClient) DelCmsCategory(ctx context.Context, in *DelCmsCategoryReq, opts ...grpc.CallOption) (*DelCmsCategoryResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DelCmsCategoryResp)
	err := c.cc.Invoke(ctx, EcommerceService_DelCmsCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ecommerceServiceClient) GetCmsCategoryById(ctx context.Context, in *GetCmsCategoryByIdReq, opts ...grpc.CallOption) (*GetCmsCategoryByIdResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCmsCategoryByIdResp)
	err := c.cc.Invoke(ctx, EcommerceService_GetCmsCategoryById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ecommerceServiceClient) SearchCmsCategory(ctx context.Context, in *SearchCmsCategoryReq, opts ...grpc.CallOption) (*SearchCmsCategoryResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchCmsCategoryResp)
	err := c.cc.Invoke(ctx, EcommerceService_SearchCmsCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EcommerceServiceServer is the server API for EcommerceService service.
// All implementations must embed UnimplementedEcommerceServiceServer
// for forward compatibility
type EcommerceServiceServer interface {
	// -----------------------CMS内容分类表-----------------------
	AddCmsCategory(context.Context, *AddCmsCategoryReq) (*AddCmsCategoryResp, error)
	UpdateCmsCategory(context.Context, *UpdateCmsCategoryReq) (*UpdateCmsCategoryResp, error)
	DelCmsCategory(context.Context, *DelCmsCategoryReq) (*DelCmsCategoryResp, error)
	GetCmsCategoryById(context.Context, *GetCmsCategoryByIdReq) (*GetCmsCategoryByIdResp, error)
	SearchCmsCategory(context.Context, *SearchCmsCategoryReq) (*SearchCmsCategoryResp, error)
	mustEmbedUnimplementedEcommerceServiceServer()
}

// UnimplementedEcommerceServiceServer must be embedded to have forward compatible implementations.
type UnimplementedEcommerceServiceServer struct {
}

func (UnimplementedEcommerceServiceServer) AddCmsCategory(context.Context, *AddCmsCategoryReq) (*AddCmsCategoryResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddCmsCategory not implemented")
}
func (UnimplementedEcommerceServiceServer) UpdateCmsCategory(context.Context, *UpdateCmsCategoryReq) (*UpdateCmsCategoryResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCmsCategory not implemented")
}
func (UnimplementedEcommerceServiceServer) DelCmsCategory(context.Context, *DelCmsCategoryReq) (*DelCmsCategoryResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelCmsCategory not implemented")
}
func (UnimplementedEcommerceServiceServer) GetCmsCategoryById(context.Context, *GetCmsCategoryByIdReq) (*GetCmsCategoryByIdResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCmsCategoryById not implemented")
}
func (UnimplementedEcommerceServiceServer) SearchCmsCategory(context.Context, *SearchCmsCategoryReq) (*SearchCmsCategoryResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchCmsCategory not implemented")
}
func (UnimplementedEcommerceServiceServer) mustEmbedUnimplementedEcommerceServiceServer() {}

// UnsafeEcommerceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EcommerceServiceServer will
// result in compilation errors.
type UnsafeEcommerceServiceServer interface {
	mustEmbedUnimplementedEcommerceServiceServer()
}

func RegisterEcommerceServiceServer(s grpc.ServiceRegistrar, srv EcommerceServiceServer) {
	s.RegisterService(&EcommerceService_ServiceDesc, srv)
}

func _EcommerceService_AddCmsCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddCmsCategoryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EcommerceServiceServer).AddCmsCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EcommerceService_AddCmsCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EcommerceServiceServer).AddCmsCategory(ctx, req.(*AddCmsCategoryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EcommerceService_UpdateCmsCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCmsCategoryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EcommerceServiceServer).UpdateCmsCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EcommerceService_UpdateCmsCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EcommerceServiceServer).UpdateCmsCategory(ctx, req.(*UpdateCmsCategoryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EcommerceService_DelCmsCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelCmsCategoryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EcommerceServiceServer).DelCmsCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EcommerceService_DelCmsCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EcommerceServiceServer).DelCmsCategory(ctx, req.(*DelCmsCategoryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EcommerceService_GetCmsCategoryById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCmsCategoryByIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EcommerceServiceServer).GetCmsCategoryById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EcommerceService_GetCmsCategoryById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EcommerceServiceServer).GetCmsCategoryById(ctx, req.(*GetCmsCategoryByIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EcommerceService_SearchCmsCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchCmsCategoryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EcommerceServiceServer).SearchCmsCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EcommerceService_SearchCmsCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EcommerceServiceServer).SearchCmsCategory(ctx, req.(*SearchCmsCategoryReq))
	}
	return interceptor(ctx, in, info, handler)
}

// EcommerceService_ServiceDesc is the grpc.ServiceDesc for EcommerceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EcommerceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ecommerce.EcommerceService",
	HandlerType: (*EcommerceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddCmsCategory",
			Handler:    _EcommerceService_AddCmsCategory_Handler,
		},
		{
			MethodName: "UpdateCmsCategory",
			Handler:    _EcommerceService_UpdateCmsCategory_Handler,
		},
		{
			MethodName: "DelCmsCategory",
			Handler:    _EcommerceService_DelCmsCategory_Handler,
		},
		{
			MethodName: "GetCmsCategoryById",
			Handler:    _EcommerceService_GetCmsCategoryById_Handler,
		},
		{
			MethodName: "SearchCmsCategory",
			Handler:    _EcommerceService_SearchCmsCategory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cms_category.proto",
}
